#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo ".env not found at $ENV_FILE" >&2
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

export SUPABASE_URL="${SUPABASE_URL:-${VITE_SUPABASE_URL:-}}"
export SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-${VITE_SUPABASE_ANON_KEY:-}}"
export SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-${VITE_SUPABASE_SERVICE_ROLE_KEY:-}}"
export FLIGHTPLANDATABASE_API_KEY="${FLIGHTPLANDATABASE_API_KEY:-${VITE_FLIGHTPLANDATABASE_API_KEY:-}}"
export OPENAIP_CLIENT_KEY="${OPENAIP_CLIENT_KEY:-${VITE_OPENAIP_CLIENT_KEY:-}}"
export SIMBRIEF_API_KEY="${SIMBRIEF_API_KEY:-${VITE_SIMBRIEF_API_KEY:-}}"
export PROCEDURE_DATA_API_KEY="${PROCEDURE_DATA_API_KEY:-${VITE_PROCEDURE_DATA_API_KEY:-}}"
export PROCEDURE_DATA_API_URL="${PROCEDURE_DATA_API_URL:-${VITE_PROCEDURE_DATA_API_URL:-}}"
export AIRPORT_REFERENCE_API_KEY="${AIRPORT_REFERENCE_API_KEY:-${VITE_AIRPORT_REFERENCE_API_KEY:-}}"
export OURAIRPORTS_DATA_URL="${OURAIRPORTS_DATA_URL:-${VITE_OURAIRPORTS_DATA_URL:-}}"
export OURAIRPORTS_NAVAIDS_DATA_URL="${OURAIRPORTS_NAVAIDS_DATA_URL:-${VITE_OURAIRPORTS_NAVAIDS_DATA_URL:-}}"
export FAA_CIFP_API_KEY="${FAA_CIFP_API_KEY:-${VITE_FAA_CIFP_API_KEY:-}}"
export FAA_CIFP_DATA_URL="${FAA_CIFP_DATA_URL:-${VITE_FAA_CIFP_DATA_URL:-}}"
export FAA_CIFP_CYCLE="${FAA_CIFP_CYCLE:-${VITE_FAA_CIFP_CYCLE:-}}"
export ROUTE_API_RATE_LIMIT_PER_MINUTE="${ROUTE_API_RATE_LIMIT_PER_MINUTE:-10}"

: "${SUPABASE_URL:?SUPABASE_URL or VITE_SUPABASE_URL is required in .env}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY or VITE_SUPABASE_ANON_KEY is required in .env}"
: "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY or VITE_SUPABASE_SERVICE_ROLE_KEY is required in .env}"

if ! command -v supabase >/dev/null 2>&1; then
  echo "supabase CLI not found in PATH" >&2
  exit 1
fi

cd "$ROOT_DIR"

secret_args=(
  "SUPABASE_URL=$SUPABASE_URL"
  "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
  "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY"
  "FLIGHTPLANDATABASE_API_KEY=$FLIGHTPLANDATABASE_API_KEY"
  "OPENAIP_CLIENT_KEY=$OPENAIP_CLIENT_KEY"
  "ROUTE_API_RATE_LIMIT_PER_MINUTE=$ROUTE_API_RATE_LIMIT_PER_MINUTE"
)

if [[ -n "$SIMBRIEF_API_KEY" ]]; then
  secret_args+=("SIMBRIEF_API_KEY=$SIMBRIEF_API_KEY")
fi

if [[ -n "$PROCEDURE_DATA_API_KEY" ]]; then
  secret_args+=("PROCEDURE_DATA_API_KEY=$PROCEDURE_DATA_API_KEY")
fi

if [[ -n "$PROCEDURE_DATA_API_URL" ]]; then
  secret_args+=("PROCEDURE_DATA_API_URL=$PROCEDURE_DATA_API_URL")
fi

if [[ -n "$AIRPORT_REFERENCE_API_KEY" ]]; then
  secret_args+=("AIRPORT_REFERENCE_API_KEY=$AIRPORT_REFERENCE_API_KEY")
fi

if [[ -n "$OURAIRPORTS_DATA_URL" ]]; then
  secret_args+=("OURAIRPORTS_DATA_URL=$OURAIRPORTS_DATA_URL")
fi

if [[ -n "$OURAIRPORTS_NAVAIDS_DATA_URL" ]]; then
  secret_args+=("OURAIRPORTS_NAVAIDS_DATA_URL=$OURAIRPORTS_NAVAIDS_DATA_URL")
fi

if [[ -n "$FAA_CIFP_API_KEY" ]]; then
  secret_args+=("FAA_CIFP_API_KEY=$FAA_CIFP_API_KEY")
fi

if [[ -n "$FAA_CIFP_DATA_URL" ]]; then
  secret_args+=("FAA_CIFP_DATA_URL=$FAA_CIFP_DATA_URL")
fi

if [[ -n "$FAA_CIFP_CYCLE" ]]; then
  secret_args+=("FAA_CIFP_CYCLE=$FAA_CIFP_CYCLE")
fi

supabase secrets set "${secret_args[@]}"
supabase functions deploy route-provider-gateway
